name = Inkfront
description = A 3 column layout with a prominent hero region.
preview = preview.png
template = inkfront-layout

; Regions
regions[branding]       = Branding
regions[navigation]     = Navigation bar
regions[header]         = Header
;regions[hero]           = Hero
;regions[neu]                   = neu
;regions[meistgekauft]    = meistgekauft
regions[highlighted]    = Highlighted
regions[help]           = Help
regions[content]        = Content
regions[sidebar_first]  = First sidebar
regions[sidebar_second] = Second sidebar
regions[footer]         = Footer

; Stylesheets
stylesheets[all][] = css/layouts/inkfront/inkfront.layout.css
stylesheets[all][] = css/layouts/inkfront/inkfront.layout.no-query.css
